### ISSUE TITLE
使用LETNet 网络 和 camvid 数据集运行不起来。

### ISSUE THREAD

**Issue by sunmingqi-1** [XU-GITHUB-curry/LETNet#4]
# 1. 先把这里修改成 camvid 图片的格式
![image](https://github.com/XU-GITHUB-curry/LETNet/assets/79261103/3b5a3d0b-2e69-4465-9185-149be71947d5)

# 2. 首先在这里报错：
![image](https://github.com/XU-GITHUB-curry/LETNet/assets/79261103/0dbc226e-ccc2-4b03-a295-af3dd3ddc771)

报错内容如下：
```
Traceback (most recent call last):
  File "/home/pc_stu2/Projects/LETNet/Network/model/LETNet.py", line 440, in <module>
    summary(model, (3, 360,480))
  File "/home/pc_stu2/anaconda3/envs/letnet/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/pc_stu2/anaconda3/envs/letnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pc_stu2/Projects/LETNet/Network/model/LETNet.py", line 414, in forward
    output4 = self.upsample_1(output4 + self.LC3(output3))  # output3: 2,32,23,64  LC3: 2,16,23,64  2,16,32,64(error)  # output3: 2,32,32,64  LC3: 2,32,32,64  2,16,32,64(error)
RuntimeError: The size of tensor a (32) must match the size of tensor b (16) at non-singleton dimension 1
```
修改了下面这个地方（不知道对不对），这个错误就消失了，但出现了新的错误：
![image](https://github.com/XU-GITHUB-curry/LETNet/assets/79261103/6eec1ad1-9d63-48c9-a734-a8962307552d)
把LongConnection第二个参数改为了32，这个错就消失了。

# 3. 第一步修改后的错误：
![image](https://github.com/XU-GITHUB-curry/LETNet/assets/79261103/e32d0dfa-1926-4698-830b-bc3ec71e0573)
报错如下：

```
/home/pc_stu2/anaconda3/envs/letnet/bin/python /home/pc_stu2/Projects/LETNet/Network/model/LETNet.py 
Traceback (most recent call last):
  File "/home/pc_stu2/Projects/LETNet/Network/model/LETNet.py", line 440, in <module>
    summary(model, (3, 360,480))
  File "/home/pc_stu2/anaconda3/envs/letnet/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/pc_stu2/anaconda3/envs/letnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pc_stu2/Projects/LETNet/Network/model/LETNet.py", line 420, in forward
    output5 = self.upsample_2(output5 + self.LC2(output2))  # output5 2,16,46,60  LC2: 2,16,45,60 output2 2,128,45,60  # output5 2,16,64,128  LC2: 2,16,64,128 output2 2,128,64,128
RuntimeError: The size of tensor a (46) must match the size of tensor b (45) at non-singleton dimension 2

```

**Comment by AAAdecade** [comment]
朋友您好！在复现过程中遇到了奇怪的报错，请问这个问题应该如何解决？求教
![image](https://github.com/user-attachments/assets/fe3c8b9f-6e10-4788-9e44-760f330cef53)

**Comment by Kyochilian** [comment]
> 朋友您好！在复现过程中遇到了奇怪的报错，请问这个问题应该如何解决？求教 ![image](https://private-user-images.githubusercontent.com/145337236/348172685-fe3c8b9f-6e10-4788-9e44-760f330cef53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMjM2MDcsIm5iZiI6MTczMTMyMzMwNywicGF0aCI6Ii8xNDUzMzcyMzYvMzQ4MTcyNjg1LWZlM2M4YjlmLTZlMTAtNDc4OC05ZTQ0LTc2MGYzMzBjZWY1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQxMTA4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTkyODI3YmY4ZWNkZWQ4ZmU2MTQwYjVmNDE5ZGMxN2NmMDU5MzZmYWI2ZjA1NjgxNDRmMTMzM2E5YjdhYzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.scGeBd1Yulwvh0fe-2-9yJaKpWL_atI5h0ZGSUuusyc)

beacause the author dont add the model "model.ESPNet_v2".the code only have the model 'model.ESPNet',you can delete it,but the code hasnt run yet there also existed other wrong problems

**Comment by LeoAkun** [comment]
因为camvid这个数据集图像是360，下采样后变成了奇数45;另一个是偶数46，这两个没办法相加，就报错了。cityscape数据集应该没问题。在417行加上if output5.shape[2:] != output2.shape[2:]:
            output5 = F.interpolate(output5, size=output2.shape[2:], mode='bilinear', align_corners=False)这俩代码就可以了
