### ISSUE TITLE
ModuleNotFoundError：没有名为 'model.ESPNet_v2

### ISSUE THREAD

**Issue by Dylan22731** [XU-GITHUB-curry/LETNet#9]
ModuleNotFoundError： No module named 'model.ESPNet_v2

**Comment by Dylan22731** [comment]
Traceback (most recent call last):
  File "train.py", line 398, in <module>
    train_model(args)
  File "train.py", line 215, in train_model
    lossTr, lr = train(args, trainLoader, model, criteria, optimizer, epoch)
  File "train.py", line 326, in train
    output = model(images)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/public/home/deeplearning/baseline/LETNet/Network/model/LETNet.py", line 411, in forward
    output4 = self.upsample_1(output4 + self.LC3(output3))
RuntimeError: The size of tensor a (32) must match the size of tensor b (16) at non-singleton dimension 1
deeplearning@29c7778beff5:~/baseline/LETNet/Network$ 
报这个错 我都不知道作者是怎么跑起来的哈哈

**Comment by Dylan22731** [comment]
这是我在camvid数据集上的结果 test_model_946
Mean IoU: 0.6800
Per class IoU: 0.9213	0.8127	0.3607	0.9442	0.8010	0.7517	0.4304	0.4298	0.8491	0.5874	0.5917

**Comment by board-man644** [comment]
请问你这个问题是怎么解决的

**Comment by Dylan22731** [comment]
> 请问你这个问题是怎么解决的

尝试复现一下其他的代码吧
